# Generated by Django 4.0.6 on 2022-07-27 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_order_delete_orders_product_orders'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='orders',
            field=models.ManyToManyField(blank=True, null=True, to='main_app.order'),
        ),
    ]
