# Generated by Django 4.0.6 on 2022-07-27 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_remove_product_orders_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='orders',
            field=models.ManyToManyField(blank=True, null=True, to='main_app.order'),
        ),
    ]
