# Generated by Django 4.0.6 on 2022-07-28 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_remove_product_image_remove_product_orders_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='orders',
            field=models.ManyToManyField(blank=True, null=True, to='main_app.order'),
        ),
    ]
