# Generated by Django 4.0.6 on 2022-07-28 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0008_product_orders'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cart',
        ),
    ]
