# Generated by Django 4.0.6 on 2022-08-04 20:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_review'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='orders',
        ),
    ]
